#### zeros()
##### – 괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화

##### 없을 경우 설치법
##### !pip install numpy

In [24]:
import numpy as np

# y = np.zeros(shape=(10,2), dtype=np.int8)
y = np.zeros(10)
y

# x = np.array([1,2,3])
# type(x)
# x.shape


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### mean() : 배열에 저장된 원소들의 평균값을 계산

In [36]:
import numpy as np

list_1 = [1,2,3]
x = np.array(list_1)
np.mean(x)
x.mean()
x.shape

(3,)

#### array() Numpy 형식으로 배열의 원소를 입력할 때는 반드시 리스트 형식으로 입력

In [43]:
x = np.array([1,2,3, 3])
y = np.array((1,2,3))
z = np.array({12,3,4})
a = np.array({"a":"b","a":"c"})
print(x,y,z,a)

[1 2 3 3] [1 2 3] {3, 12, 4} {'a': 'c'}


#### reshape() 배열을 원하는 모양으로 생성

In [50]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b, b.shape, '\n', c, c.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4) 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


#### reshape() 3차원 배열 만들기

In [60]:
a = np.arange(1,9)
b = a.reshape(2,2,2)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
a = np.arange(1,13)
print(a)
b = a.reshape(3,2,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


###### reshape 의미

###### reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며, 현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [58]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###### reshape를 활용하는 경우를 보다 보면 입력 인수로 -1이 들어간 경우가 종종 있다. reshape()의 ‘-1’이 의미하는 바는, 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

In [67]:
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [64]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [65]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### ones()

In [82]:
y = np.ones([4,3])
# z = y*0.3
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Numpy 배열의 슬라이싱

In [86]:
list1 = [[1,11],[2,12],[3,13],[4,14]]
print(list1[:][1])
print(list1[:,1])

[2, 12]


TypeError: list indices must be integers or slices, not tuple

In [110]:
list1 = [[1,11],[2,12],[3,13],[4,14]]
arr = np.array(list1)
print(arr)
# print(arr[:,1])
print(arr[1:3][1])
print(arr[1:4])

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]]
[ 3 13]
[[ 2 12]
 [ 3 13]
 [ 4 14]]


##### math 모듈의 sqrt()와 numpy 모듈의 sqrt() 비교


In [117]:
import math
math.sqrt(2)
math.sqrt([2,3,4])

TypeError: must be real number, not list

In [120]:
import numpy as np
np.sqrt(2)
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [123]:
import numpy as np

x = np.zeros(15)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [126]:
y = np.zeros([5,3])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [135]:
#원소를 4로만드는(3,5)형태로 reshape
y = np.zeros([5,3])
z = y.reshape([3,5])
z =+4
print(z)

4


### 전치행렬
##### transpose() – 행과 열을 교환하여 얻어지는 행렬 – 행렬의 값들을 주대각선을 기준으로 위치를 바꾼 행렬을 의미

In [142]:
import numpy as np

ary = np.array([[1,2],[3,4]])
print(ary)
print('\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2]
 [3 4]]


[[1 3]
 [2 4]]


In [144]:
ary = np.array([[1,2,3],[4,5,6]])
print(ary)
print('\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


##### 2개 배열에 대한 연산
###### – 2개 배열에 저장된 내용을 인덱스별로 계산
###### – 선형대수학의 사칙연산과 동일하게 작동 – 곱셈도 같은 원리로 동작

In [148]:
import numpy as np

x = np.array((3,4,5))
y = np.array((1,2,3))
print(x+y)
print(x*y)
print(x//y)
print(x%y)
print(x**y)

[4 6 8]
[ 3  8 15]
[3 2 1]
[0 0 2]
[  3  16 125]


In [160]:
x = np.array((3,4,5))
x **= 5
x += 6
print(x)

[ 249 1030 3131]


##### 인덱싱

In [162]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:,1])

[4 5 6]
[2 5 8]


##### 2개의 Numpy 배열 간의 계산

In [168]:
# x의 1행과 y의 3행을 더한 값을 출력한다.
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[0,:]+y[2,:])
# x의 2열과 y의 3행을 곱한 값을 출력한다.
print(x[:,1]*y[2,:])
# print(x[:,1]*y[2])

[ 9 11 13]
[16 45 80]


In [169]:
a = np.array([10,20,30,40,60])
b = a >30

print(b)

[False False False  True  True]


#### linspace()

In [189]:
import numpy as np

ary = np.random.random(5)
print(ary)

[0.49754331 0.07083704 0.82471989 0.01813293 0.01481175]


In [248]:
#[0, 1] 범위에서 균일한 분포
a = np.random.rand(5)
print(a)
print('\n')
b = np.random.rand(2, 3)
print(b, b.shape)

[0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]


[[0.26455561 0.77423369 0.45615033]
 [0.56843395 0.0187898  0.6176355 ]] (2, 3)


In [247]:
a = np.random.randint(2, size=5)
print(a)

b = np.random.randint(2, 4, size=5)
print(b)

c = np.random.randint(1, 5, size=(2, 3))
print(c)

[1 1 0 1 1]
[2 2 3 2 3]
[[4 2 4]
 [4 3 4]]


#### random.seed()¶

In [470]:
import numpy as np

np.random.seed(0)

print(np.random.rand(2, 3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [511]:
np.random.seed(0)
a = np.random.rand(5)
b = np.random.rand(5)
print(a,b)

# print(a >0.12)
# print(np.all(a>0.12))
# print(a)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ] [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]


#### any()와 all()의 비교

In [512]:
a = np.random.rand(5)
print(a)
print(a>0.12)
print(np.all(a>0.12))

[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
[ True  True  True  True False]
False


In [461]:
a = np.random.rand(5)
print(a>0.9)
print(np.any(a>0.9))

[False False False False  True]
True


#### linspace()

##### 시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분 0과 12를 포함한 그 사이의 값들을 선형적으로 분배하여 모두 4개의 원소를 갖는 배열을 생성
##### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [522]:
np.linspace(0,12,4)

array([ 0.,  4.,  8., 12.])

In [523]:
# retstep=True이면 샘플 간의 간격을 출력

In [520]:
np.linspace(2, 13, 5, endpoint = False)

array([ 2. ,  4.2,  6.4,  8.6, 10.8])